### ISSUE TITLE
request.js uses overlapping error handling flows

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb-examples#19]
See: https://github.com/bigchaindb/bigchaindb-examples/blob/master/client/lib/js/utils/request.js#L18

One would have to listen for a `.catch` in the returned promise of the function, as well as on a `try-catch` before the return.

Resolve this to use only one of those two error handling flows (I'd use purely promises)

**Comment by diminator** [comment]
**side note**: we really need to make sure we are inline with the [ILP spec](https://github.com/interledger/rfcs/tree/master/0004-ledger-plugin-interface)

or, if our changes are dramatically, we should try to alter the spec

**Comment by sohkai** [comment]
This shouldn't make too much of a difference in regards to the ILP spec; just the plugin would handle the error case a little bit differently.
