### ISSUE TITLE
python3 setup.py install failed.

### ISSUE THREAD

**Issue by ppiyakk2** [bigchaindb/bigchaindb-examples#3]
I tried to install example following README.md, and I got an error.

I tried in OS X and Ubuntu but same result.

`error: Setup script exited with error in BigchainDB setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers`

**Comment by diminator** [comment]
Maybe try:

```
pip install -e .
```

**Comment by ppiyakk2** [comment]
@diminator  I solved this problem supported by @vrde 

https://github.com/bigchaindb/bigchaindb/issues/236

**Comment by diminator** [comment]
cool, closing this issue
